/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/graffiti_alley_v3.glb --typescript 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Graffiti_alley_v3(props: any) { // mude de 'Model' para 'Graffiti_alley_v3'
  const { nodes, materials } = useGLTF('/models/graffiti_alley_v3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[4.346, 22.443, -21.456]} rotation={[0.048, 0.001, 3.114]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['graffiti_alley-metashape_uvs-m']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['graffiti_alley-metashape_uvs-m']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['graffiti_alley-metashape_uvs-m']} />
        <mesh geometry={nodes.Object_2.geometry} material={materials['graffiti_alley-metashape_uvs-m']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['graffiti_alley-metashape_uvs-m']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['graffiti_alley-metashape_uvs-m']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['graffiti_alley-metashape_uvs-m']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['graffiti_alley-metashape_uvs-m']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['graffiti_alley-metashape_uvs-m']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['graffiti_alley-metashape_uvs-m']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['graffiti_alley-metashape_uvs-m']} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[25.895, -24.712, -32.708]} rotation={[0, 0.016, -0.01]} scale={[20.556, 20.556, 1.8]} />
    </group>
  )
}

useGLTF.preload('/graffiti_alley_v3.glb')
